version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ledgerpay
      POSTGRES_USER: ledger
      POSTGRES_PASSWORD: ledger
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledger"]
      interval: 5s
      retries: 10
  ledger-service:
    build: ./ledgerpay-backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ledgerpay
      DB_USER: ledger
      DB_PASSWORD: ledger
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
